### ISSUE TITLE
Any plans to support Swagger 2.X?

### ISSUE THREAD

**Issue by ishaigor** [gigaSproule/swagger-gradle-plugin#103]
With the replacement of the annotations it is no longer working.
https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Migration-from-1.5

**Comment by gigaSproule** [comment]
Yes, I do plan on supporting it once I've cleared down some more bugs. There already is an issue open for this, #55. So I'll close this as a duplicate.

If however you wish to submit a PR that does support swagger 2, feel free to do so.
