### ISSUE TITLE
'code' parameter in ApiOperation ignored for POST requests

### ISSUE THREAD

**Issue by dcp65** [gigaSproule/swagger-gradle-plugin#108]
Just noticed that this is an issue in version 1.0.4. It works as expected if a I roll back to 0.1.9.

I have a number of APIs that are annotated like this:

```
@POST
@ApiOperation(value = 'Create foo',
    notes = 'Creates a foo.',
    nickname = 'createFoo',
    response = FooModel,
    code = 201)
```
In 0.1.9, the response object in generated swagger.json looks like this, as expected:

```
"responses" : {
    "201" : {
    "description" : "successful operation",
    "schema" : {
    "$ref" : "#/definitions/FooModel"
    }
  }
}
```

In 1.0.4, it looks like this:

```
"responses" : {
   "200" : {
   "description" : "successful operation",
   "schema" : {
   "$ref" : "#/definitions/FooModel"
   }
 }
}
```
So it seems that `code=201` in the `@ApiOperation` annotation is being ignored.

**Comment by gigaSproule** [comment]
I will add a test for this, see what happens. Is expect it to pick it up perfectly fine, but clearly not.

**Comment by gigaSproule** [comment]
So turns out that with Spring, this worked fine (as the reader picked read the value), whereas JAX-RS reader was missing a line, so wasn't reading the value. I've pushed the fix, so will be fixed in the next release.
