### ISSUE TITLE
Gradle now uses separate output directories for each JVM language, but this build assumes ..

### ISSUE THREAD

**Issue by gunnarahlberg** [gigaSproule/swagger-gradle-plugin#117]
There is somewhere a usage of separate output directories. Apparently, Gradle is unhappy about this

Steps to reproduce:
1. setup a build.gradle with 
```groovy
plugins {
    id 'java'
    id 'com.benjaminsproule.swagger' version '1.0.4'
}
```

2. Run the build
> ./gradlew clean 

**Expected**
No errors. No warnings

**Actual** 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

3. Following the instructions gives more information
> ./gradlew clean --warning-mode all

> Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0."

**Versions**
- Gradle 4.10.2 
- com.benjaminsproule.swagger:1.0.4

**Comment by gigaSproule** [comment]
This should already be fixed, but I'll have to check it out (may only be fixed on develop)

**Comment by gigaSproule** [comment]
```groovy
if (project.sourceSets.main.output.getProperties()['classesDirs']) {
    project.sourceSets.main.output.classesDirs.each {
        if (it.exists()) {
            urls += it.toURI().toURL()
        }
    }
} else {
    urls += project.sourceSets.main.output.classesDir.toURI().toURL()
}
```
So if I comment out the `classesDir`, it still shows that message. It seems that for some reason, the if statement (`project.sourceSets.main.output.getProperties()` specifically) is causing it to show as well.

This if statement is only here in case anyone is still using pre-gradle 4.x where it was only 1 directory. When as long as it still works, I'd rather not remove it.
