### ISSUE TITLE
version 1.0.4 of this plugin does not play nicely with artifactory

### ISSUE THREAD

**Issue by aol-nnov** [gigaSproule/swagger-gradle-plugin#118]
Here are excerpts from my build.gradle:

```
buildscript {
  repositories {
    maven { url 'https://plugins.gradle.org/m2/' }
  }
  dependencies {
    classpath 'gradle.plugin.com.benjaminsproule:swagger-gradle-plugin:1.0.4'
  }
}

apply plugin: 'java'
apply plugin: 'com.jfrog.artifactory'
apply plugin: 'com.benjaminsproule.swagger'

swagger {
  //...
}

dependencies {
  compile 'my-local:artefact:0.0.1-SNAPSHOT'
}

artifactory {
  publish {
    //...
  }
  resolve {
  //...
  }
}
```

with 1.0.4 my artefacts are not resolved, with 1.0.3 I'm getting `Cannot change dependencies of configuration ':xxx:compile' after it has been resolved.`

If it's relevant, spring boot 2.1.0.RELEASE with spring-cloud Greenwich.M1 are also used in this project.

Any glue on this? Thanks in advance!

**Comment by gigaSproule** [comment]
In 1.0.4 I made some changes in how the plugin works, so it doesn't mess around with dependencies early on, which is what the error you see in 1.0.3 states.

As for the error of not resolving, are you using a standard artefact setup? I.e. just a jar or jar + sources or jar + test jar, etc.?

I can't think of any reason why this plugin would have issues with that.

**Comment by aol-nnov** [comment]
nothing fancy on my end:

```
publishing {
        publications {
            mavenJava(MavenPublication) {
                artifactId project.name
                from components.java
            }
        }
    }

artifactory {
        contextUrl = "${artifactory_contextUrl}" 
        publish {
            repository {
                repoKey = 'gradle-dev-local'
                username = "${artifactory_user}"
                password = "${artifactory_password}"
                maven = true

            }
            defaults {
                publications('mavenJava')
                publishArtifacts = true
                publishPom = true
            }
        }
        resolve {
            repository {
                repoKey = 'gradle-dev-local'
                username = "${artifactory_user}"
                password = "${artifactory_password}"
                maven = true
            }
        }
    }
```

**Comment by aol-nnov** [comment]
@gigaSproule here is a full  [build.gradle](
https://gist.github.com/aol-nnov/f12ddeb63f0cb74a6c6b1fdf0d8a7743) of my root project (it's a multimodule setup)

what I'm actually trying to achieve is to automatically build swagger.json, then generate Feign client and package it into separate jar and finally publish all that to my artifactory host.

I'm kinda lost in all that stuff and still can't make it work automatically..
Ideally I'd like to hook all generation and compilation of generated sources into build task.

**Comment by aol-nnov** [comment]
A side note about artifactory and my local repos:

there is a "Set Me Up" button in the artifactory web gui and it generates exactly the same excerpt, so, it seems to me like a proposed method to connect artifactory repos into projects.

I'll try your advice anyway, but just wanted to let you know.

**Comment by gigaSproule** [comment]
Yeah, I've used artifactory a lot professionally and they try and make things "easier" but they end up being very bespoke. I've always found it easier to use the standard, non-implementation specific approach.

**Comment by aol-nnov** [comment]
I've removed artifactory `resolve` configuration in favour of
```
maven {
            url "${artifactory_contextUrl}/gradle-dev/"
            credentials {
                username("${artifactory_user}")
                password("${artifactory_password}")
            }
        }
```
and it, ahem, resolved the resolution issue :-D

Still I'm having problems to wire tasks correctly...
As I told earlier, I'd like to generate swagger.json and feign client during `gradle build`, but no luck so far...

Could you please advise me the right direction to dig into?

**Comment by gigaSproule** [comment]
Glad I've been able to solve 1 problem.

Again, I'm at work, so trying to do this via my phone, but you should be able to do something like `tasks.build.dependsOn(tasks.generateSwaggerDocumentation)` to get it to generate swagger docs on build (or `tasks.build.doLast(tasks.generateSwaggerDocumentation)`

**Comment by aol-nnov** [comment]
So, I've finally sorted it out... Kind of.. Not sure if I've done it right, but it works :)

Here it goes:

`clientJar` task (from `build.gradle`, that I posted earlier) depends on newly created `buildClient` task of `JavaCompile` type which depends on `generateSwaggerCodeClient` which depends on `generateSwaggerDocumentation`.

Results of `generateSwaggerDocumentation` are put in a separate `sourceSet`. (I thought that main app is run to generate `swagger.json`, so generated sources should go separate way. Am I right here?)

Meanwhile I've discovered cool gradle plugin for printing task dependencies, which helped me a lot - https://github.com/dorongold/gradle-task-tree

```
./gradlew  :notifications:build :notifications:taskTree

:notifications:build
+--- :notifications:assemble
|    +--- :notifications:bootJar
|    |    \--- :notifications:classes
|    |         +--- :notifications:compileJava
|    |         \--- :notifications:processResources
|    \--- :notifications:jar
|         +--- :notifications:classes
|         |    +--- :notifications:compileJava
|         |    \--- :notifications:processResources
|         \--- :notifications:clientJar
|              +--- :notifications:buildClient
|              |    \--- :notifications:generateSwaggerCodeClient
|              |         +--- :notifications:generateSwaggerDocumentation
|              |         |    \--- :notifications:classes
|              |         |         +--- :notifications:compileJava
|              |         |         \--- :notifications:processResources
|              |         \--- :notifications:resolveSwaggerTemplate
|              \--- :notifications:classes
|                   +--- :notifications:compileJava
|                   \--- :notifications:processResources
\--- :notifications:check
     \--- :notifications:test
          +--- :notifications:classes
          |    +--- :notifications:compileJava
          |    \--- :notifications:processResources
          \--- :notifications:testClasses
               +--- :notifications:compileTestJava
               |    \--- :notifications:classes
               |         +--- :notifications:compileJava
               |         \--- :notifications:processResources
               \--- :notifications:processTestResources
```

**Comment by gigaSproule** [comment]
If it works, it works. The beauty of gradle is that it's flexible to work however you want it (as long as you're willing to put in the effort 😉).

Generally I have generated code packaged and published rather than committed into VCS, but if it's something you want, then it makes sense.

**Comment by aol-nnov** [comment]
Seems to be some misunderstanding :) I did not intend to store generated code into VCS and did not stated such here.

My goal was to generate sources, compile them and publish compiled jars into artifactory.

Thank you for your tips, which made it happen! :)

**Comment by gigaSproule** [comment]
I wasn't meaning to suggest you were, just wanting to clarify how I've dealt with generated stuff before (just generating into build dir and packaging).

Glad it's all fixed!
