### ISSUE TITLE
Swagger attachSwaggerArtifact don´t deploy JSON type object as described

### ISSUE THREAD

**Issue by morpheus9999** [gigaSproule/swagger-gradle-plugin#12]
As described :
> You can instruct swagger-gradle-plugin to deploy the generated swagger.json by adding the following to your build.gradle:
swaggerDirectory = '${project.rootDir}/swagger-ui'
attachSwaggerArtifact = true
The above setting attaches the generated file to Gradle for install/deploy purpose with swagger-ui as classifier and **json** as type

task  Added ability to attach swagger artifact:
GenerateSwaggerDocsTask.groovy:

project.task('createSwaggerArtifact', type: **Jar**, dependsOn: project.tasks.classes) {

                        classifier = classifierName
	                from swaggerFile
}

**Comment by gigaSproule** [comment]
I will have to take a look into this.

**Comment by gigaSproule** [comment]
Been a bit busy recently, but this is still on my radar to look into. Sorry it's taking me a while to get round to it.

**Comment by gigaSproule** [comment]
I've started work on this in `feature/implement-attach-swagger-artifact`

**Comment by gigaSproule** [comment]
Also noticed this [issue](https://github.com/kongchen/swagger-maven-plugin/issues/501) the other day

**Comment by morpheus9999** [comment]
Thats not the same problem.
I am using the maven plugin and it's working , deploy JSON and YAML to NEXUS as expected.

<groupId>com.github.kongchen</groupId>
<artifactId>swagger-maven-plugin</artifactId>
<version>3.1.4</version>
...
<outputFormats>json,yaml</outputFormats>
<attachSwaggerArtifact>true</attachSwaggerArtifact>

**Comment by gigaSproule** [comment]
Sorry, wasn't saying it was, I just wanted to add that to this so I know there was/is a possible problem with the maven one as well.

This is actually the one of the features that doesn't use the maven plugin (which is probably why it isn't working).

**Comment by gigaSproule** [comment]
I know it's taking me ages to look at this, but I will get round to this soon.

**Comment by gigaSproule** [comment]
This should be working since v1.0.1 onwards, so going to close this issue.
