### ISSUE TITLE
Can't discover JSON security definition file when in project resources

### ISSUE THREAD

**Issue by plechev** [gigaSproule/swagger-gradle-plugin#15]
The following configuration results in JSON parse error which is caused by inability to discover the file _service-security.json_. The problem is present in all cases with file placed either in _main/resources_, _main/java_ or at project's root. 
Further debugging reveals that the classloader used when the plugin executes has no access to the project's files, be it resources or Java source files.    

Code in _build.gradle_: 

```
swagger {
    apiSource {
        locations = ['my.package']
        basePath = '/api'
        info {
            title = "Service API"
            version = project.version
        }
        jsonExampleValues = true 
        swaggerDirectory = "${project.buildDir}/generated/docs/"
        outputFormats = "json,yaml"
        securityDefinition {
            json = "/service-security.json" // attempted with and without the leading slash 
        }
    }
}
```

**Comment by gigaSproule** [comment]
I will take a look at it. If the `classloader` didn't have access, it wouldn't generate the swagger document at all. Maybe a specific config setup that causes it to break.

**Comment by plechev** [comment]
Good point. However when debugging I noticed that the class on which we call `getResourceAsStream` would not return any resource/source from the project. 
Perhaps an option can be added to refer to the file directly, bypassing the classloader altogether. For example: 
```
        securityDefinition {
            jsonPath = "${project.rootDir}/service-security.json" 
        }
```

**Comment by gigaSproule** [comment]
I've made the necessary changes in branch `feature/add-json-path-to-security-definition`, so when your PR for the maven plugin is merged in and released, I will merge that in.

**Comment by Ilia-Antipenkov** [comment]
The maven plugin PR was merged. Please continue, @gigaSproule =).

**Comment by gigaSproule** [comment]
Merged

**Comment by gigaSproule** [comment]
And now released as 0.1.2

**Comment by iantipenkov** [comment]
Looks like it's not working since the underlying change in the swagger-maven-plugin hasn't been released yet. When swagger-maven-plugin 3.1.6 is released and the dependency here is updated, this should start working.

**Comment by gigaSproule** [comment]
Ha! Obviously! It really was late last night...

**Comment by ThatGuy32** [comment]
any update on this?
seems like version  0.1.2. not working because jsonPath not working
and i dont understand how to use securityDefinitions with json and version 0.1.1

**Comment by gigaSproule** [comment]
I'm currently on holiday (in not so sunny northern ireland) so I can't really check this out, but it's waiting on the maven plugin to be released for this to work. The latest release did at least work last time I checked, but I can try again when I get home.

**Comment by ThatGuy32** [comment]
Thanks for the fast answer :)

seems like SecurityDefinition::setJsonPath doesn't exist yet 
i uploaded an example project: https://github.com/ThatGuy32/swaggerplugin
maybe you can help me, i have no idea how to add security definitions

Have fun on holiday! :)

**Comment by plechev** [comment]
The jsonPath property comes from the maven plugin which this one is wrapping. We need to make sure the change in the maven plugin is released before attempting to use it here.

**Comment by gigaSproule** [comment]
As @plechev has already stated, the json path stuff is new in 0.1.2, so won't work, which was my bad for merging and releasing preemptively. When I'm next able to, I'll try and get a working snapshot if any are available.

**Comment by ThatGuy32** [comment]
yeah, so i tryed it with 0.1.1, but i dont understand how to use securityDefinition with

        securityDefinition {
            json = '/securityDefinition.json'
        }

where should i put the securityDefinition.json file?
i tryed it with resources etc. but i cannot get it to work

**Comment by nalmeida84** [comment]
Hi guys, any news?

I'm waiting to kongchen next plugin version 3.1.6 to solve the classpath file loading problem.

**Comment by plechev** [comment]
I chased the next release of the Maven plugin about a month ago. No news so far. Maybe can give them headsup again?

**Comment by nalmeida84** [comment]
Probably... I'm using the 3.1.6 snapshot for now :/

**Comment by gigaSproule** [comment]
I've changed how this plugin includes files/classes, so it might be worth trying the latest version (0.1.9)

**Comment by ethiery** [comment]
Hi @gigaSproule,
I am still having this issue, even when using 0.1.9. Any chance you might be able to fix that soon?
Thank you for your plugin, it otherwise works very well :+1:

**Comment by gigaSproule** [comment]
@ethiery What is that you have set to? Also, I'm hoping to get the re-write released this week, so that may fix it, but I'd like to try and replicate it first.

**Comment by set321go** [comment]
I have tried this with v1.0.0 and it does appear to be working. I get security Definitions in the generated `swagger.json` file. 

You have 2 options when using `json = 'security-definition.json` this is referencing a file on the classpath, so for example if your `security-definitions.json` is in the `resources` directory you don't need to specify any directories.

If you want to reference a file you can use `jsonPath = "${buildDir}/resources/main/security-definition.json"` and it will load the file from the file system. 

If someone else could verify this is working I will close this issue

**Comment by gigaSproule** [comment]
The samples show that this works from the classpath, so this can be closed. As @set321go has stated, there are 2 options, use the classpath or specify a full path.
