### ISSUE TITLE
property swaggerFileName is not supported

### ISSUE THREAD

**Issue by trasa** [gigaSproule/swagger-gradle-plugin#16]
The Maven plugin (https://github.com/kongchen/swagger-maven-plugin/blob/master/README.md) has a property `swaggerFileName` that, along with `swaggerDirectory` controls where the swagger output json file ends up (by default, a file called `swagger.json`)

However this property is not exposed & implemented in the gradle wrapper, see: 
https://github.com/gigaSproule/swagger-gradle-plugin/blob/master/src/main/groovy/com/benjaminsproule/swagger/gradleplugin/GenerateSwaggerDocsTask.groovy#L89

**Comment by gigaSproule** [comment]
That's a feature of the latest version of the maven plugin. It is on my list to add these functionalities.

**Comment by gigaSproule** [comment]
I'd actually already done this as part of the upgrade to 3.1.5, so just merged it in (with a slight tweak)

**Comment by gigaSproule** [comment]
I've also released it

**Comment by gigaSproule** [comment]
I take it is all working, so closing this.
