### ISSUE TITLE
properties in swagger.json are sorted alphabetically instead of order of appearance

### ISSUE THREAD

**Issue by sniffertine** [gigaSproule/swagger-gradle-plugin#187]
Hi There

I use    
`plugin id 'com.benjaminsproule.swagger' version '1.0.8'`
to generate my swagger.json. This all works fine, but the order of properties of my DTO class ends up in alphabetic order. 

Instead, I would like them to be in the same order as my fields in the DTO class. Is there a configuration that I missed to accomplish this, or may this be an encancement?

**Comment by Vladiatro** [comment]
I agree. It's strange to see e.g. `start` coming after `end`, especially in the API generated by the Swagger definition.
