### ISSUE TITLE
Java 8 incompatibility

### ISSUE THREAD

**Issue by eugenekainara** [gigaSproule/swagger-gradle-plugin#188]
After upgrading to latest(1.0.10) version I'm getting following errors:
```
FAILURE: Build failed with an exception.

* What went wrong:
java.lang.UnsupportedClassVersionError: com/benjaminsproule/swagger/gradleplugin/GradleSwaggerPlugin has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> com/benjaminsproule/swagger/gradleplugin/GradleSwaggerPlugin has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

Debug info:
1. java -version
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)
```
2. ./gradlew --version
```
------------------------------------------------------------
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_252 (AdoptOpenJDK 25.252-b09)
OS:           Mac OS X 10.15.6 x86_64
```

**Comment by gigaSproule** [comment]
Our should be built targeting 1.7, so I'll take a look at that.

**Comment by Siqaos** [comment]
Hello, same issue with 1.0.10

```
FAILURE: Build failed with an exception.

* What went wrong:
> java.lang.UnsupportedClassVersionError: com/benjaminsproule/swagger/gradleplugin/GradleSwaggerPlugin has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
java -version
```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

**Comment by gigaSproule** [comment]
That's weird, because I've got a branch that is running against JDK 8 and it's fine...

**Comment by crazycreak** [comment]
same problem, we have java 11 and i get the following error:

**Comment by eugenekainara** [comment]
@gigaSproule please check following [repo](https://github.com/eugenekainara/swagger-plugin-test) - I've tried to reproduce my errors in docker env - so you should be able to check what's wrong in this  case.

**Comment by gigaSproule** [comment]
I finally found a bit of time to sort out the release workflow, so the next build is run off jdk 8. Hopefully that will fix it. The release step is still failing, but it's just a simple git config fix I'll do tonight if I have time

**Comment by tspoeri** [comment]
Just tried version 1.0.10 with Java 8 and still get the error
```
> java.lang.UnsupportedClassVersionError: com/benjaminsproule/swagger/gradleplugin/GradleSwaggerPlugin has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
Any news on this?

**Comment by gigaSproule** [comment]
Hey, I've just been swamped with everyday stuff. For some reason, the build runs perfectly fine but no matter what I try to get this released, I'm hitting issues. Before, it was a much simpler project layout, but then Travis nor CircleCI could get a passing build. More complicated layout and we have successful builds, but no release. Still on it though.

**Comment by gigaSproule** [comment]
@eugenekainara your test repo is now fixed with 1.0.11 (or at least doesn't fail with this error). Can you, @tspoeri and/or @crazycreak  (and whoever else) verify this and then this can be closed.

**Comment by eugenekainara** [comment]
Checked with 1.0.11 and 1.0.12 - build is passing now. Will check in real project this evening.

**Comment by tspoeri** [comment]
Build works with 1.0.12 and Java 8, thanks!
