### ISSUE TITLE
Swagger.json for Spring RestControllers is not generated

### ISSUE THREAD

**Issue by cleankod** [gigaSproule/swagger-gradle-plugin#19]
At first I thought my configuration is somewhat wrong. So I've taken the `sample` directory and generated `swagger.json` - worked perfectly. Then I changed the controller to Spring-ish, not JAX-RS:
```java
package com.benjaminsproule.sample;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@Api(value = "/sample", description = "Sample REST for Integration Testing")
public class SampleResource {
    @RequestMapping("/sample")
    @ApiOperation(value = "Return hello message", response = String.class)
    public String home() {
        return "{\"Hello\": \"World!\"}";
    }
}
```
And suddenly the `swagger.json` does not contain `paths` section whatsoever. I even changed the configuration:
```groovy
swagger {
    apiSource {
        springmvc = true
        swaggerApiReader = 'com.github.kongchen.swagger.docgen.reader.SpringMvcApiReader'
        //...
    }
}
```
But it didn't help. Also tried without `swaggerApiReader` - no luck here either. So my question is - how to generate the `swagger.json` for Spring controllers?

**Comment by cleankod** [comment]
Got it, need to explicitly define the method:
```java
@RequestMapping(path = "/sample", method = RequestMethod.GET)
```

**Comment by gigaSproule** [comment]
Glad you found out what the problem was. I will expand the samples to include this. I've created an issue (#20) to remind me to do it.

**Comment by cleankod** [comment]
@gigaSproule - is it possible to generate from Spring controllers without adding Swagger's `@Api` annotations?
