### ISSUE TITLE
Could not set unknown property 'swaggerFilename'

### ISSUE THREAD

**Issue by HYChou0515** [gigaSproule/swagger-gradle-plugin#22]
No problem when I don't put swaggerFilename="something"

But when I put it into apiSource, this message pops up:

> Could not set unknown property 'swaggerFilename' for com.benjaminsproule.swagger.gradleplugin.extension.ApiSourceExtension(apiModelPropertyAccessExclusionsList:null, typesToSkipList:null, attachSwaggerArtifact:false) of type com.benjaminsproule.swagger.gradleplugin.extension.ApiSourceExtension.

    apiSource {
        springmvc = false
        locations = [ 'abcdefg' ]
        info {
            title = 'Swagger Gradle Plugin Sample'
            version = 'v1'
            description = 'This is a sample.'
        }
        outputFormats="yaml"
        swaggerDirectory = "${project.rootDir}/generated/swagger-ui"
        swaggerFilename = "swagger123"
    }

version: 0.1.2

**Comment by gigaSproule** [comment]
I'll try and take a look at it later today.

**Comment by gigaSproule** [comment]
It has to be `swaggerFileName`. I've updated the ReadMe

**Comment by gigaSproule** [comment]
I'll close this as it works in the sample project.
