### ISSUE TITLE
Task is slow

### ISSUE THREAD

**Issue by set321go** [gigaSproule/swagger-gradle-plugin#23]
When running the `generateSwaggerDocumentation` task it takes a long time. It looks like this is because `Reflections` is scanning the world!
```
> Task :authtoken-rest:generateSwaggerDocumentation
Putting task artifact state for task ':authtoken-rest:generateSwaggerDocumentation' into context took 0.0 secs.
Executing task ':authtoken-rest:generateSwaggerDocumentation' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Resolving dependency management for configuration 'runtime' of project 'authtoken-rest'
Excluding []
Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0
Reflections took 2 ms to scan 2 urls, producing 13 keys and 20 values 
Reflections took 4027 ms to scan 294 urls, producing 14115 keys and 76380 values 
Reflections took 4054 ms to scan 294 urls, producing 14115 keys and 76380 values 
Reflections took 4016 ms to scan 294 urls, producing 14115 keys and 76380 values 
Reflections took 4019 ms to scan 294 urls, producing 14115 keys and 76380 values 
Reflections took 3919 ms to scan 294 urls, producing 14115 keys and 76380 values 
Reflections took 4311 ms to scan 294 urls, producing 14115 keys and 76380 values 
```

I suspect was caused by gradle i'm running the latest 4.1 in this project but i have seen this issue with all projects running 4+

**Comment by set321go** [comment]
Ok so the problem *in my build* is that 

```
    private ClassLoader prepareClassLoader() {
        List<URL> urls = new ArrayList<>();
        project.configurations.runtime.resolve().each {
            if (!it.name.endsWith('.pom')) {
                urls.add(it.toURI().toURL())
            }
        }
        urls.add(project.sourceSets.main.output.classesDir.toURI().toURL())
        return new URLClassLoader(urls as URL[], this.getClass().getClassLoader())
    }
```
`project.configurations.runtime.resolve()` resolves every jar in the gradle classpath (126 in my case),  for my project i'm pretty sure it will work with just the project line. I'm not entirely sure why this is done anyway, is it so that you discover annotations from classes that are inherited?

*NB* Any idea how you test a plugin in a project with the new plugins block? I't doesn't appear to support snapshots.

**Comment by gigaSproule** [comment]
The reason why it goes through everything is that there might be API endpoints in an inherited JAR. Might be worth adding a flag on whether to scan everything or not.

**Comment by set321go** [comment]
That makes sense.

Maybe an exclude would be more flexible (It makes sense you might have annotations in dependencies). It could just expand on what you have already, so the default could be `*.pom` 

It's entirely possible that the plugin hasn't got any slower but gradle has got faster which is why i'm now noticing this.

**Comment by set321go** [comment]
Maybe something like this https://github.com/gigaSproule/swagger-gradle-plugin/compare/master...set321go:excludes

I tried to get this into my project to test it  but i can't get it to look in any of the right places.

**Comment by gigaSproule** [comment]
I've ended up just using your code. Would have been easier to just send a PR.

**Comment by set321go** [comment]
So I tried the exclude filter, it does work, which is great but it doesn't solve the problem. After some investigation this weekend I was able to debug one of my builds and I think i've isolated the issue. 

The reflections code in`ApiSourceExtension#getValidClasses` is being called once with the locations list and the classloader, this is the scan that finds 2 urls.

Looking into the `swagger-maven-plugin` `JaxrsReader#updateTagDescriptions` creates a `Reflections` object with an empty package and no classloader, I assume this uses the default classloader which would be gradle. The `updateTagDescriptions` method is called inside the `getMethods` for loop of `read` so it is executed for every method in that class that is annotated with `ApiOperation`.

I don't have a solution, I think this is a problem with the maven plugin, at the very least is should cache everything it finds on the first scan of `Reflections("").getTypesAnnotatedWith(SwaggerDefinition.class)` given that the classpath won't change between iterations of the loop. I have opened an issue https://github.com/kongchen/swagger-maven-plugin/issues/534 hopefully I can get some time to work on it

**Comment by gigaSproule** [comment]
I guess when we manage to sort out #30 this can be closed as well

**Comment by set321go** [comment]
After testing the refactored plugin from #30 the reflections performance is significantly improved, we can see it's still finding the same number of keys and values 👍  but much faster.

```
Reflections took 1 ms to scan 1 urls, producing 0 keys and 0 values 
Reflections took 2 ms to scan 1 urls, producing 13 keys and 20 values 
Reflections took 0 ms to scan 1 urls, producing 0 keys and 0 values 
Reflections took 1 ms to scan 1 urls, producing 13 keys and 20 values 
Reflections took 0 ms to scan 1 urls, producing 0 keys and 0 values 
Reflections took 3 ms to scan 1 urls, producing 13 keys and 20 values 
```

The behaviour is slightly different now because it's scanning each location seperately instead of doing them all at once, this could be changed if it leads to some problems down the road.

**Comment by set321go** [comment]
https://github.com/gigaSproule/swagger-gradle-plugin/pull/39
