### ISSUE TITLE
API basic authorization definition

### ISSUE THREAD

**Issue by y-luis** [gigaSproule/swagger-gradle-plugin#24]
I need to define basic authorization security for my API. As I understand from documentation, I would have to set my Gradle settings file like this:

```
swagger {
    apiSource {
    ...
        securityDefinition {
            name = 'basicAuth'
            type = 'basic'
       	}
   
}
```
but this results in error:

`No signature of method: com.github.kongchen.swagger.docgen.mavenplugin.SecurityDefinition.setJsonPath() is applicable for argument types: (null) values: [null]`

Which it is suppose to be an alternative definition using a file. How do I define a single basic authorization in Gradle settings file?

I am using version 1.5.16.

Thanks.

**Comment by set321go** [comment]
FYI https://github.com/gigaSproule/swagger-gradle-plugin/issues/15

I have a hack setup to deal with this issue that might be of use.

```
import groovy.json.JsonSlurper
import groovy.json.JsonBuilder
import java.nio.file.Paths

//massage the swagger file to include security definitions
task massageSwaggerFile {
    doLast {
        JsonSlurper slurper = new JsonSlurper()
        def swaggerDef = Paths.get("${project(':tenant-rest').buildDir}/swagger/tenant/swagger.json").withReader { reader ->
            slurper.parse(reader)
        }

        def securityDef = Paths.get("${projectDir}/src/main/swagger-resources/security-definition.json").withReader { reader ->
            slurper.parse(reader)
        }

        swaggerDef["securityDefinitions"] = securityDef

        new File("${buildDir}/swagger").mkdir() //make the swagger directory
        def output = new File("${buildDir}/swagger/swagger.json")
        output.write(new JsonBuilder(swaggerDef).toPrettyString())
    }
}
```

**Comment by gigaSproule** [comment]
This was a screw up as part of #15. This has been fixed now.
