### ISSUE TITLE
Generating from Spring controllers and models without Swagger's @Api... annotations

### ISSUE THREAD

**Issue by cleankod** [gigaSproule/swagger-gradle-plugin#26]
Setting the `springmvc` to `true` does not work. Setting the `swaggerApiReader` to  `com.github.kongchen.swagger.docgen.reader.SpringMvcApiReader` also does not work.

Therefore, my question is - how to generate `swagger.json` without the `@Api...` annotations?

**Comment by magicliang** [comment]
I have a lot of @Api... annotations, and I still can not generate any meaningful swagger.json.

configuration is like this:

```groovy
swagger {
    apiSource {
        springmvc = true
        locations = [ 'path to my controller package with swagger annotation controllers' ]
        schemes = [ 'http', 'https' ]
        //host = 'www.example.com:8080'
        //basePath = '/api'
        info {
            title = 'Registry center server'
            version = 'v0.9x'
            description = 'A registry center for service governance.'
            contact {
                email = 'myname@xxx.com'
                name = 'myname'
            }
        }

        outputPath = "${project.rootDir}/generated/document.html"
        swaggerDirectory = "${project.rootDir}/generated/swagger-ui"
        swaggerApiReader = 'com.github.kongchen.swagger.docgen.reader.SpringMvcApiReader'
        //modelConverters = [ 'io.swagger.validator.BeanValidator' ]
        attachSwaggerArtifact = true
    }
}
```

       Then just "gradle generateSwaggerDocumentation",
       I see a nearly-empty swagger.json like this:

```json
{
  "swagger" : "2.0",
  "info" : {
    "description" : "A registry center for service governance.",
    "version" : "v0.9x",
    "title" : "Registry center server",
    "contact" : {
      "name" : "myname",
      "email" : "myname@xxx.com"
    }
  },
  "schemes" : [ "http", "https" ]
}
```     

       If I uncomment "modelConverters" line, I see "Could not find custom model converter io.swagger.validator.BeanValidator".

       Any idea about this?

**Comment by gigaSproule** [comment]
Sorry for not really getting round to this, I've been crazy busy (wife having a really bad pregnancy). I'm going to try and create some more samples where this can be shown nicely (and obviously raise any issues).

**Comment by gigaSproule** [comment]
I've just created a sample project and I'm getting the same issue. At least I now have something to go with

**Comment by gigaSproule** [comment]
The sample is now working. I forgot to add in the Swagger annotations... it's been a long week

**Comment by gigaSproule** [comment]
Having looked into the underlying code (the swagger-maven-plugin), it requires the swagger annotations to produce the swagger documentation, which makes perfect sense. @cleankod `springmvc` only sets whether the to look for REST endpoints that are defined by Spring or JAX-RS annotations.

@magicliang Can you check against the sample projects and see if there is anything obviously different? Also, can you try with the latest version as well (0.1.9)?

**Comment by mrkoston** [comment]
@magicliang i used to have the same problem, for me the only solution was to set the output directory to the buildpath, like this:


swagger {
    apiSource {
        springmvc = false
        locations = [ 'com.dms.api.rest3.workspace' ]
        schemes = [ 'http', 'https' ]
        host='http://devindmachine1103.uy-it00531.dev.fusionlifecycle.autodesk.com:8080'
        basePath='/api/v3/'
        info {
            title = 'FLC-360'
            version = 'v1'
            description = 'This is a sample.'
            termsOfService = 'http://www.example.com/termsOfService'
            contact {
                email = 'email@email.com'
                name = 'Name'
                url = 'http://www.example.com'
            }
            license {
                url = 'http://www.apache.org/licenses/LICENSE-2.0.html'
                name = 'Apache 2.0'
            }
        }
        securityDefinition {
            name = 'OXYGEN'
            type = 'oauth2'
        }
         swaggerDirectory = "${project.buildDir}/swagger-ui"
    }
}


And i didn't set the output path (According to maven's plugin, it was not necesary).

and i only added the swagger-annotations depndency, like this: 

    compile (group: "io.swagger", name: "swagger-annotations", version: "1.5.8")

didn't used swagger core.

**Comment by gigaSproule** [comment]
@cleankod I was getting the same behaviour in maven as this plugin. If you are seeing something different, can you please update?

**Comment by magicliang** [comment]
Using latest plugin I can generate swagger.json with meanningfu content now:

plugins {
    id "com.benjaminsproule.swagger" version "1.0.4"
}

But I still can not use modelConverters

        // modelConverters = [ 'io.swagger.validator.BeanValidator' ]

Can you please tell me which dependency should I introduce in my build.gradle to eliminate the gradle error.

**Comment by gigaSproule** [comment]
Have you got the modelConverter you are trying to use in the scripts classpath?
E.g.
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.custom:model-converter:1.0.0'
    }
}
```

**Comment by magicliang** [comment]
@gigaSproule I am using the default "io.swagger.validator.BeanValidator".

```
buildscript {
    ext {
        springBootVersion = '1.5.3.RELEASE'
    }
    repositories {
        mavenCentral()
        maven { url 'http://maven.aliyun.com/nexus/content/groups/public/' }
        maven { url 'http://artifactory.intra.xiaojukeji.com/artifactory/libs-release/' }
        maven { url 'http://artifactory.intra.xiaojukeji.com/artifactory/libs-snapshot/' }
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath("io.swagger.validator.BeanValidator")
    }

}
```

does not work(of course it shouldn't work and the example dose not change anything of buildscript).

So what is correct way to use default `io.swagger.validator.BeanValidator` as show in example?

**Comment by cleankod** [comment]
`1.0.4` seems to generate `swagger.json` just fine, without any additional Swagger annotations. Thanks!
