### ISSUE TITLE
unknown property "classesDirs"

### ISSUE THREAD

**Issue by sebastienvermeille** [gigaSproule/swagger-gradle-plugin#27]
Hello
I tried to use this plugin (which seems great) but I have a problem related to gradle more than the plugin itself but the documentaton doesn't talk about that:

```shell
* What went wrong:
Execution failed for task ':generateSwaggerDocumentation'.
> Could not get unknown property 'classesDirs' for main classes of type org.gradle.api.internal.tasks.DefaultSourceSetOutput.

```

Any idea of solution ?

I simply copied the swagger {} example.

**Comment by kgilmer** [comment]
+1

**Comment by kgilmer** [comment]
I was able to overcome this by using the version of gradle bundled in this package, like so from the sample directory: `$ ../gradlew generateSwaggerDocumentation`.  I would imagine the root cause of this issue is related to the Gradle version.

**Comment by sebastienvermeille** [comment]
@kgilmer nice I will have a look on it thank you!

**Comment by garyschulteog** [comment]
Same problem.   FWIW, this seems to be broken in 0.1.4 (from Sept 7 2017).  If you explicitly specify version 0.1.2 it seems to work.

**Comment by sebastienvermeille** [comment]
@garyschulteog thanks I will give a try

**Comment by y-luis** [comment]
Same happened. Solved using 0.1.2.

**Comment by gigaSproule** [comment]
What version of Gradle are you using?

**Comment by sebastienvermeille** [comment]
@gigaSproule great news :) I am ready to test it. 

I would be happy to help you with a PR but I really don't have enough experience with gradle lifecycle and stuff for now.

**Comment by gigaSproule** [comment]
@sebastienvermeille my only real knowledge is from doing this little project because we needed it where I used to work. No harm in just giving it a go and sending it over. Worst case scenario, I add some comments to a PR (I'll be nice :smile: ).

**Comment by gigaSproule** [comment]
Released as 0.1.6 (had a bit of fun with the release plugin...)

**Comment by sebastienvermeille** [comment]
Great I will try it this weekend ! (Yes I love my job that much :) )

**Comment by gigaSproule** [comment]
Have you had any time to test this?

**Comment by sebastienvermeille** [comment]
Sure I did it right yesterday it works like a charm 👍  thank you very much !
