### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by bbilger** [gigaSproule/swagger-gradle-plugin#3]
Hi,
Thanks for developing the plugin!
I have one request, though: The plugin adds a project dependency to swagger-core which itself depends on quite heavy libraries like guava. Any chance to "reduce" the added project dependency to swagger-annotations since I don't see any necessity to add a dependency to swagger-core in a project using the plugin.

**Comment by gigaSproule** [comment]
I can definitely look into that. When I originally did this, it was a quick thing we needed for work so it's not had much love. But I'll get onto your request tomorrow (friday). Hopefully I'll have some time when I get to work to do it.

**Comment by bbilger** [comment]
Great! Thanks.
Just to be a little more precise: I am talking about the dependency to swagger-core added in GradleSwaggerPlugin.

**Comment by gigaSproule** [comment]
I've had a quick look at what I can do to exclude stuff, but unfortunately the maven plugin (which I'm basically just wrapping around) uses some of the swagger-core classes. I'll see which classes aren't really being used, but it's going to take quite a bit of digging to get it sorted. At some point I'd like to get the maven plugin logic out of the wrapped maven code so I can just import a nice library, but whether that will ever happen without me needing to maintain all that code I don't know (which was the point of me just wrapping around the maven plugin in the first place).

**Comment by bbilger** [comment]
Hi,
Thanks for checking. I think there's a misunderstanding, I don't mean the dependencies of the plugin itself but the dependencies the plugin adds to projects using the plugin:
GradleSwaggerPlugin:
project.dependencies.add('compile', 'io.swagger:swagger-core:1.5.4', {
            exclude group: 'javax.ws.rs', module: 'jsr311-api'
        })

This adds a dependency to swagger-core and it's dependencies to any project using the plugin.
IMO this is not required. Technically no such dependency needs to be added at all I'd say but adding a dependency to swagger-annotations makes sense since it's a requirement to use those annotations for the plugin to work.

**Comment by gigaSproule** [comment]
Ah, totally forgot that was in there. Yeah, I'm not sure why that is bringing so much in. Probably left over from previous attempts that were never sorted. I'll get that changed over the weekend.

**Comment by gigaSproule** [comment]
I've made that change now and it's been pushed as version 0.0.6. Sorry it's taken so long. Was on a stag do last weekend and been really busy this week.

**Comment by bbilger** [comment]
Thank you!
