### ISSUE TITLE
Refactor away the maven swagger plugin code

### ISSUE THREAD

**Issue by set321go** [gigaSproule/swagger-gradle-plugin#30]
I keep running into issues that are in the maven-swagger-plugin which seems to have a low level of maintenance and a number of open issues. I decided to bite the bullet and merge the two plugins. 

I started by bringing all the code from the maven-swagger-plugin and then spent some time refactoring the java code into groovy. I have been adding tests and refactoring the gradle-swagger-plugin along the way.

I have added the jacoco plugin to the build but I didn't bring any of the tests from the maven-swagger-plugin because they were generally terrible, I have added quite a few tests around the model objects for the plugin and some tests around skipping and artifact generation. 

This is still a WIP (hence the 🍌 ' s) I am going to continue adding tests, especially for the spring generation as there are currently none. Let me know if your interested in this work. I plan to move across to this for my projects and it would be great if it becomes part of your project but I can understand that it's a significant departure from the current plugin.

https://github.com/set321go/swagger-gradle-plugin/tree/remove-kongchen-dependency

**Comment by gigaSproule** [comment]
It's definitely been on my to do list, but with a baby on the way, I've struggled to find the time. I'll definitely take a PR to a branch and play with it if that's OK?

**Comment by set321go** [comment]
Yeah np. can you create a branch for me to target and I will create a PR for you.

I also upgraded all the dependencies and gradle (apart from handlebars, as i wanted to get a working api docs test as its 3 major versions behind)

**Comment by gigaSproule** [comment]
:+1: I'll also give you permissions on the branch so it can stay up to date. After all, I don't want all your hard work to go to waste and we can PR into it like a real OS project :P

**Comment by gigaSproule** [comment]
Created a PR (#31) but has some conflict issues, which would most likely be from the recent changes I did...

**Comment by set321go** [comment]
This should probably have a beta/RC/major version association so people don't accidentally start using it, not sure what the gradle plugin convention is.

**Comment by set321go** [comment]
Tested this refactoring fixed:
- #23 
- #15 I don't understand the details enough but there is now a test that exercises loading the definition file relative to the classpath. This logic now also ignores the 'name' field (Deprecated) when loading from a securityDefinintion. The name is now set to be the object name. This differs from the gradle config which takes 'name:type' (but has other limitations)
- #12 There is now a test that checks the artifact is generated when the flag is set. It does not  yet validate the contents of that jar. I did make a code change here though because I saw the jar had no contents. the `from` now refers to a directory not a file.

**Comment by gigaSproule** [comment]
#12 should result in the swagger file being pushed (not a jar). I didn't ever get it working because at the time I didn't need it.

**Comment by set321go** [comment]
So i was thinking about how to release this version without breaking everyone because your docs currently say `com.benjaminsproule:swagger-gradle-plugin:+` anyone using that will pickup this version. It would be preferable to test this version out in the wild as a beta version first.

**Comment by gigaSproule** [comment]
I'm hoping to have some time over the weekend to take a better look at this. If we're happy with it, we shouldn't be worried about releasing it out in the wild. But I think we should at least up the major version when we release it and update the `README` to specify `com.benjaminsproule:swagger-gradle-plugin:1.+` instead for future cases.

**Comment by gigaSproule** [comment]
Finally got round to having a look. There was only 1 obvious issue that I could see, so I've had a crack at it in PR #34. Have to admit, I've only got a my rubbish laptop at the moment, so it was a bit of a struggle.

**Comment by set321go** [comment]
https://github.com/gigaSproule/swagger-gradle-plugin/pull/39
