### ISSUE TITLE
Used it for non-spring mvc or jaxrs , it generates spec but it has no data on resources

### ISSUE THREAD

**Issue by Shaindil** [gigaSproule/swagger-gradle-plugin#36]
It looks even though I pass the package information, it does not pick up resources classes and add it to the swagger spec. What could be the reasons that it does not pick up the resources from the given packages.

Here is the swagger spec generated
{
  "swagger" : "2.0",
  "info" : {
    "description" : "This is a sample.",
    "version" : "v1",
    "title" : "Swagger Gradle Plugin Sample",
    "termsOfService" : "http://www.example.com/termsOfService",
    "contact" : {
      "name" : "Name",
      "url" : "http://www.example.com",
      "email" : "email@email.com"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host" : "http://localhost:8080",
  "basePath" : "/restTestApp/bookapi",
  "schemes" : [ "http", "https" ]
}

Here is the build.gradle file
 defaultTasks 'generateSwaggerDocumentation'
 
 // Apply the java plugin to add support for Java
apply plugin: 'java'

repositories {
        jcenter()
    }

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.benjaminsproule:swagger-gradle-plugin:0.1.9'
    }
}
apply plugin: 'com.benjaminsproule.swagger'

dependencies {

	compile 'io.swagger:swagger-annotations:1.5.17'	
	compile 'io.swagger:swagger-core:1.5.17'
	compile 'io.swagger:swagger-jaxrs:1.5.17'
	compile 'io.swagger:swagger-models:1.5.17'
	compile 'com.google.code.gson:gson:2.8.2'
	compile 'com.squareup.okhttp:okhttp:2.7.5'
	compile 'com.squareup.okhttp:logging-interceptor:2.7.5'
	compile 'joda-time:joda-time:2.9.9'

	testCompile 'org.testng:testng:6.13.1'
	

}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java', 'books/src/main/java']
        }
    }
    
    test {
    	java{
    	    srcDirs = ['src/test']
    	}
    }
}

swagger {
    apiSource {
    	println 'inside swagger apisource'
        springmvc = false
        locations = [ 'oracle.igcs.resource' ]
        schemes = [ 'http', 'https' ]
        host = 'http://localhost:8080'
        basePath = '/restTestApp/bookapi'
        info {
            title = 'Swagger Gradle Plugin Sample'
            version = 'v1'
            description = 'This is a sample.'
            termsOfService = 'http://www.example.com/termsOfService'
            contact {
                email = 'email@email.com'
                name = 'Name'
                url = 'http://www.example.com'
            }
            license {
                url = 'http://www.apache.org/licenses/LICENSE-2.0.html'
                name = 'Apache 2.0'
            }
        }
        /**
            Support classpath or file absolute path here.
            1) classpath e.g: "classpath:/markdown.hbs", "classpath:/templates/hello.html"
            2) file e.g: "${project.rootDir}/src/main/resources/markdown.hbs", "${project.rootDir}/src/main/resources/template/hello.html"
        **/
        
        //templatePath = "${project.rootDir}/src/test/resources/strapdown.html.hbs"
        //outputPath = "${project.rootDir}/generated/document.html"
        swaggerDirectory = "${project.rootDir}/generated/swagger-ui"
        println "${project.rootDir}"
        //swaggerApiReader = 'com.wordnik.swagger.jaxrs.reader.DefaultJaxrsApiReader'
        //modelConverters = [ 'io.swagger.validator.BeanValidator' ]
        // attachSwaggerArtifact = true - WILL BE ADDED IN THE FUTURE
    }
}

test  {
	
   // enable TestNG support (default is JUnit)
   useTestNG()
   // listen to events in the test execution lifecycle
  beforeTest { descriptor ->
     logger.lifecycle("Running test: " + descriptor)
  }

**Comment by gigaSproule** [comment]
I assume that your classes are annotated correctly with `@Api` etc?

**Comment by gigaSproule** [comment]
Just a follow up, as I've not heard anything back, is that you are using `@Api`, but nothing else? In which case this plugin will not currently work without a custom API reader.

**Comment by gigaSproule** [comment]
Is my assumption above correct? If you are using `@Api` then maybe this should be a feature where we check all files annotated with `@Api`?

**Comment by gigaSproule** [comment]
As I've not heard anything back, I'm closing this issue. If you still feel like it's something to look at, then feel free to re-open it.
