### ISSUE TITLE
Plugin has side-effect w/ Gradle daemon

### ISSUE THREAD

**Issue by cslee00** [gigaSproule/swagger-gradle-plugin#37]
When using the Gradle daemon (default on newer Gradle versions) the plugin has some odd side effects.  Once a class is loaded once for analysis by the plugin it won't be loaded again on subsequent builds, so changes won't be picked up. 

Workaround: running Gradle with --no-daemon fixes the issue

One possible solution would be to create a new, isolated classloader an run the plugin in that, as shown here: https://discuss.gradle.org/t/how-to-separate-gradle-plugin-dependencies-and-project-dependencies/15515/4

**Comment by gigaSproule** [comment]
Hopefully going to release the re-write this week some time, so we can check this out after the release.

**Comment by set321go** [comment]
@cslee00 Do you still experience this issue with 1.0.0 the maven portions of the plugin have been refactored into the plugin.

**Comment by gigaSproule** [comment]
I'm going to close this as it's basically the same as #32 and doesn't make sense to have both open.
