### ISSUE TITLE
Multiple models with same name results in nondeterministic swagger file generation

### ISSUE THREAD

**Issue by fmotrifork** [gigaSproule/swagger-gradle-plugin#44]
I located a very interesting issue in the current implementation.

If the application that we generate swagger documentations for has multiple models with the same class name, it will result in that the swagger file generated will only contain one of the models. It seems random which of the models are chosen for the swagger generation.

This can happen if you have two different input model and output models with same name. Or to models with same name in different versions:

```
 com.xxxxxx.v1.canonical.Pet
 com.xxxxxx.v2.canonical.Pet
```

The plugin should handle this in some way. I see a couple of different options.

1. Prefix models with package until all names are unique
1. Add a running number to the model name for duplicate models
1. Throw an exception and not create any swagger docs if there are different models with same name

Best,
Frederik

**Comment by gigaSproule** [comment]
Can you provide a real example? What I'm seeing you say is that you have 2 endpoints with the same path, which produce the same response and/or take the same input?

**Comment by fmotrifork** [comment]
If i have two endpoints:

```
GET /api/v1/pets
GET /api/v2/myAwsomePets
```

And they both produce a model called `dog:

```
 com.my.package.v1.Dog  // this has a property called owner
 com.my.package.v2.Dog  // this does not.
```
But the two `dog` models does not have the same properties. (This is why i have a `v1` and a `v2` verison of them). Then i get a swagger file with two endpoints in (`/api/v1/pets` and `/api/v2/myAwsomePets`) but the swagger file will say that they both produce the same `dog` model as response. 

It seems that the plugin just chooses a random of the two `dog` models as the result. And that is chances with each generation which dog models is described as the result of _both_ endpoints. Sometime there are a owner property in the dog definition, sometimes there are not.

**Comment by set321go** [comment]
This section of the spec
```
  "definitions" : {
    "Aug" : {
      "type" : "object",
      "properties" : {
        "fields" : {
          "type" : "object",
          "additionalProperties" : {
            "$ref" : "#/definitions/Primitive"
          }
        }
      }
    },
```

I had a look yesterday, there are quite a few api/tools that are based on swagger that have a similar issue. I think the root of the issue is the spec does not have any namspacing for types, something could probably be implemented but i'm inclined to go with option 3 throw an exception.  

The spec has support for polymorphism (with use of the `discrimiator` property) if that is what is what your really trying to express otherwise give them different names. https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

**Comment by gigaSproule** [comment]
Out of curiosity, are you aware of version `0.1.9` exhibiting the same behaviour?

**Comment by mogensen** [comment]
I haven't tried this in the 0.x branch. So I cannot say if this is new behavior.

**Comment by gigaSproule** [comment]
Just tried having the package with the definition name and seeing what the swagger codegen created and it won't work. It creates the class `io.swagger.client.model.ComMyPackageV1Dog` and `io.swagger.client.model.ComMyPackageV2Dog`. Obviously this won't work for most people. Perhaps you can use different ApiSource configurations? That way you can have them separated out.
