### ISSUE TITLE
Cannot generate Swagger from Groovy or Kotlin

### ISSUE THREAD

**Issue by dcp65** [gigaSproule/swagger-gradle-plugin#45]
I'm having problems generating Swagger where the APIs are written in a language other than Java - namely Groovy or Kotlin

In these cases the generated classes are written to `build/classes/kotlin/main` or `build/classes/groovy/main`.

When I run the swagger-gradle-plugin, it seems that it cannot find the Kotlin or Groovy classes. I get an error like this:

`could not create Dir using directory from url file:/Users/dcp65/projects/myproject/build/classes/java/main. skipping.
`

Is there any way to override the build path?

I was able to generate Swagger from Groovy until upgrading swagger-gradle-plugin to 1.0.0, so perhaps something changed when the dependency on kongchen was removed.

**Comment by set321go** [comment]
Not sure why it's defaulting to java. Have you tried setting `swaggerDirectory` in the plugin task? Mine looks like `swaggerDirectory = "${buildDir}/resources/main"`

**Comment by dcp65** [comment]
Thanks @set321go, but `swaggerDirectory` is the location where the swagger.json should be written to, no? Mine is set to `"${project.buildDir}/swagger"`

**Comment by gigaSproule** [comment]
There is a sample with Kotlin, so I'm pretty sure it does work. I will give it a test.

**Comment by gigaSproule** [comment]
Fixed. Turned out I was an idiot. It wasn't picking classesDirs properly. I had it working with the kotlin sample and I have released it, so can you please check with 1.0.2?

**Comment by dcp65** [comment]
Fantastic. It's working in 1.0.2. Thanks for the fast response @gigaSproule. Great to see all the activity on this project.
