### ISSUE TITLE
Update README to explain how to use custom model converters, API readers, etc.

### ISSUE THREAD

**Issue by gigaSproule** [gigaSproule/swagger-gradle-plugin#48]
Currently, it's not obvious how to use custom classes as part of this plugin, such as custom model converters and API readers. All that is required is to add the classes to the classpath for the buildscript, e.g. to use `io.swagger.validator.BeanValidator` for the model converter:
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'io.swagger:swagger-hibernate-validations:1.5.18'
    }
}
```

**Comment by rendesg** [comment]
Thank you for this "todo comment" of yours, @gigaSproule!! I am quite new to gradle and though this seems now obvious, but I couldn't figured out myself.. :D cheers!

**Comment by gigaSproule** [comment]
I've updated the README for custom model converters and api readers.
