### ISSUE TITLE
parameters are not sort in json file

### ISSUE THREAD

**Issue by shlomialfasi** [gigaSproule/swagger-gradle-plugin#49]
the parameters inside the Operation are not sorted and therefore any generation of a swagger.json file end up with a different result.

**Comment by shlomialfasi** [comment]
[swagger-order.txt](https://github.com/gigaSproule/swagger-gradle-plugin/files/1735197/swagger-order.txt)

**Comment by gigaSproule** [comment]
Is it possible to create a PR instead of just a patch? I have very little time on my hands right now, so it's easier for me to approve a PR than to apply a patch :)

**Comment by gigaSproule** [comment]
The parameters are in order of their appearance. I don't see this being an issue and the tests always produce the same result (so there is a consistent order). Unless you can show otherwise, I am reluctant to add in ordering logic as the parameters are probably in a specific order for a reason.

**Comment by gigaSproule** [comment]
As I see this as a non-issue, I'm going to close this. If you see that they are randomly ordered, please feel free to re-open with an example (if possible).
