### ISSUE TITLE
Adding dependency

### ISSUE THREAD

**Issue by PSJMcNeill** [gigaSproule/swagger-gradle-plugin#5]
Been trying to use this plugin, I have followed your example to try and add it to my build.gradle file.

When I run it I get an error saying it cannot find the plugin.

"Could not find com.benjaminsproule:swagger-gradle-plugin:0.0.3"

Any ideas?

**Comment by gigaSproule** [comment]
I've updated the [example](https://github.com/gigaSproule/swagger-gradle-plugin/blob/master/README.md#example). I had missed out `jcenter()` as the maven repository to use and I've specified the latest version (which is 0.0.6).

I've been meaning to update this with the latest swagger-maven-plugin version, but I haven't got round to it yet. If you need it urgently, I can always give it a go later tonight.

**Comment by gigaSproule** [comment]
Didn't mean to close it XD

**Comment by PSJMcNeill** [comment]
Thanks for the quick response. Been looking everywhere for a decent grade plugin for swagger.

No rush, is it possible to still use it with the older version of the maven plugin?

**Comment by gigaSproule** [comment]
We use it and it works fine for our use case, but I don't think we're using any complicated logic. If you do find any issues, just raise issues on here and I'll try and get them fixed.

**Comment by PSJMcNeill** [comment]
Cheers much appreciated! Will give it a go tomorrow!

**Comment by PSJMcNeill** [comment]
Tried it this morning but got a version mismatch when applying the plugin, does this plugin require Java 8?

**Comment by gigaSproule** [comment]
I've upgraded to the latest, so it now supports `@Info` as well. I've only tried it with Java 8, as that's the only version we use (and it's the only one still officially supported).

**Comment by PSJMcNeill** [comment]
Ah unfortunately we are using Java 7 and still in the process of upgrading to Java 8, so will probably be a while before we can use this. Cheers anyway!

**Comment by gigaSproule** [comment]
I'll try it out with Java 7 tonight. I don't see any reason why it won't work.

**Comment by PSJMcNeill** [comment]
Thanks really appreciate it. I get the error when it runs the Apply Plugin line. Returns "Unsupported major.minor version 52.0" Which I believe is an error that it was compiled in Java 8 but is trying to be run in something older ie. Java 7

**Comment by gigaSproule** [comment]
0.0.8 now works with 1.7

**Comment by PSJMcNeill** [comment]
Unreal thanks so much! Hopefully the last question I'll have for you :)

In the plugin configuration example you seem to pass in the package directory for which it should scan.

I have tried a few different variations of this and it returns an error of Cannot cast object with class Java.lang.String to class java.util.List

**Comment by gigaSproule** [comment]
Sorry, that was an error in the example. Just need to wrap it with `[ ]`

**Comment by PSJMcNeill** [comment]
Perfect, cheers!
