### ISSUE TITLE
apiSource.outputFormats changed behavior after upgrading from 1.0.0 to 1.0.2

### ISSUE THREAD

**Issue by cpoulsen-dezide** [gigaSproule/swagger-gradle-plugin#50]
Gradle version: 4.5.1

Error:
```
* What went wrong:
A problem occurred evaluating project ':contact-center-service'.
> Cannot cast object 'json,yaml' with class 'java.lang.String' to class 'java.util.List'
```
Changing to:
`outputFormats = ['json','yaml']`

Gets things going again. I think that the 'new' syntax is more natural, but if the change is intentional then the README should be updated. 

Also specifying outputFormats = ['json,yaml'] results in a successful run with no output generated. Perhaps the input could be verified to help users.

**Comment by gigaSproule** [comment]
`outputFormats` is a list, so would have to be specified as such (hence why `['json', 'yaml']` produces a the correct output). When I have some time, I will ensure the README is correct.

**Comment by cpoulsen-dezide** [comment]
Looks good ;)
