### ISSUE TITLE
Generated tags regression after updating plugin from 1.0.0 to 1.0.2

### ISSUE THREAD

**Issue by cpoulsen-dezide** [gigaSproule/swagger-gradle-plugin#52]
Gradle version 4.5.1
Spring MVC

After plugin upgrade the generated "tags" section no longer contains the `description` property.

Output before:
```
  "host" : "localhost:8081",
  "tags" : [ {
    "name" : "customers",
    "description" : "Operations related to customers"
  }, {
    "name" : "faqs",
    "description" : "Operations for FAQs"
  }, {
...
```
Output after:
```
  "tags" : [ {
    "name" : "customers"
  }, {
    "name" : "faqs"
  }, {
...
```

The definition in the Customers controller:

```
@RestController
@RequestMapping( value = "/customers", produces = APPLICATION_JSON_UTF8_VALUE )
@Api( value = "/customers", description = "Operations related to customers",
      authorizations = { @Authorization( value = "dezideoauth",
              scopes = { @AuthorizationScope( scope = "read", description = "" ),
                         @AuthorizationScope( scope = "write", description = "" ) } ) } )
public class CustomerController
```

Maybe it is possible to compare the generated output of some complex examples to a known output during testing, to avoid introducing regressions like this.

**Comment by gigaSproule** [comment]
Thanks for the bug report, I will take a look into it. I'm hoping to find some time to increase the test coverage, but it's gone from no tests to what we have now and I have very little time. More than happy to receive a PR if you want to give it a go (but don't feel like you have to).

**Comment by gigaSproule** [comment]
It's worth pointing out that description on the Api annotation is deprecated. Of course, the plugin should still deal with it as long as it is there.

**Comment by gigaSproule** [comment]
Simple bug, I'm just updating the tests and then I can implement the fix.

**Comment by gigaSproule** [comment]
This has been fixed and should work in the next release
