### ISSUE TITLE
Error using Custom Model Converter

### ISSUE THREAD

**Issue by seazzle** [gigaSproule/swagger-gradle-plugin#57]
Hi guys,

I get the follwing error using custom model generator: 
`Could not find custom model converter com.vig.dummy.wgv.resource.CustomModelConverter`
The file file is available on the classpath and implements io.swagger.converter.ModelConverter

I am using the version 1.0.2 with Spring and JaxRs:

Here is my setup:

```
	swagger {
	    apiSource {
	        springmvc = false
	        locations = [ 
	        	'com.vig.dummy.basis.resource.gf.GeschaeftsfallResource',
	        	'com.vig.dummy.framework.produkt.konfiguration.resources.ProduktKonfigurationResource'
	        ]
	        schemes = ['http']
        host = 'localhost:8080'
        basePath = '/ngwgv'
        info {
            title = 'Vigo Next-Gen API'
            version = '1.0.0'
        }
	    swaggerDirectory = "${project.buildDir}/swagger-ui"
	    modelConverters = [ 'com.vig.dummy.wgv.resource.CustomModelConverter' ]
	    }
	}
	
	build.dependsOn generateSwaggerDocumentation
```

Can anyone help or is dealing also with this issue ?

Thx for help

**Comment by Wafflemon** [comment]
I'm not exactly sure how to fix this, but I can give some ideas that might help you fix it. It seems like your "CustomModelConverter" isn't available in your project's buildscript classpath. If that's not the issue, then you should probably look into the Gradle documentation and figure out how to get this plugin to see your model converter.

`buildscript {
  repositories {
    dependencies {
      classpath <reference your model converter here>
    }
  }
}
`

**Comment by gigaSproule** [comment]
Sorry for the late reply (still trying to get to grips with having a baby). As @Wafflemon stated, it doesn't look like it is in the classpath and would need to be added to it.

**Comment by seazzle** [comment]
@Wafflemon @gigaSproule : Many thx for your reply. This solved the issue. The generator works as expected.
Sadly I have still a problem with my ModelCoverter Implementation of swagger..
Because it is a stateful --> the typeMapping is passed via constructor injection using spring.
When gradle is loading it the member variable is null and throws a nullpointer exception.
But thats an other issue.
