### ISSUE TITLE
Could not find method findProperty() for arguments [swagger.skip]

### ISSUE THREAD

**Issue by kashishbest** [gigaSproule/swagger-gradle-plugin#58]
Hi,

I am new to swagger and gradle. I was facing the issue on running the below command. 
```code
./gradlew generateSwaggerDocumentation
```

I got the below error

* What went wrong:
Could not evaluate onlyIf predicate for task ':generateSwaggerDocumentation'.
> Could not find method findProperty() for arguments [swagger.skip] on root project .

Can someone help

**Comment by gigaSproule** [comment]
Can you post your build.gradle file? Or at least the relevant bits.

**Comment by gigaSproule** [comment]
Tests are fully created for this. For this to work, you need to run `./gradlew generateSwaggerDocumentation -Pswagger.skip=true`
