### ISSUE TITLE
Multiple apiSource produces incorrect documents

### ISSUE THREAD

**Issue by istomisgood** [gigaSproule/swagger-gradle-plugin#62]
If I have 2 controllers, each with a single GET returning different pojo responses, then the first pojo response object is used for the second controller's response object.

I have attached a diff showing the bug.

[multipleApiSourceBug.zip](https://github.com/gigaSproule/swagger-gradle-plugin/files/1913825/multipleApiSourceBug.zip)

**Comment by istomisgood** [comment]
And the fix...

[multipleApiSourceBugFix.zip](https://github.com/gigaSproule/swagger-gradle-plugin/files/1913899/multipleApiSourceBugFix.zip)

**Comment by gigaSproule** [comment]
If you create a PR with these, we can merge this in properly. I'd rather it be accredited to the right person.

**Comment by istomisgood** [comment]
Pull request created. Thanks for this great plugin.

https://github.com/gigaSproule/swagger-gradle-plugin/pull/66
