### ISSUE TITLE
Improve dependency configuration

### ISSUE THREAD

**Issue by cpoulsen-dezide** [gigaSproule/swagger-gradle-plugin#68]
Hi

I'm getting errors due to my module having a "compileOnly" dependency on something used in the controllers that the plugin should generate the swagger definition from.

It looks like the plugin always uses the "runtime" configuration, thereby missing the classes.

I'm not intimately familiar with the gradle stuff, but the dependency I need, seems to be included in the "runtimeOnly" configuration - Maybe that could be considered as well by the plugin.

I think this issue may relate to #59 where the servlet API dependencies probably also are "provided"

If this can't be handled automatically, the plugin should probably use its own configuration that extends runtime, so it is possible to control what is going on.

**Comment by cpoulsen-dezide** [comment]
Plugin version 0.1.4 resolves provided dependencies just fine, while the v1.0.2 gives an error. That seems like a regression.

**Comment by gigaSproule** [comment]
You are correct, it does check runtime dependencies. Should be a simple fix, but just need to find the time (hopefully tomorrow).

**Comment by cpoulsen-dezide** [comment]
Thank you for the quick reply! I hope it is an easy fix. I'm on vacation until next week, so do not rush it for my sake ;)

**Comment by gigaSproule** [comment]
The fix is trivial, just creating tests to prove the issue and then can prove the fix

**Comment by UnAfraid** [comment]
Sounds great!
Thanks for the fast response
