### ISSUE TITLE
excludePattern configuration for apiSource not found

### ISSUE THREAD

**Issue by danielzhaotongliu** [gigaSproule/swagger-gradle-plugin#73]
Hello,

It seems like the excludePattern configuration for apiSource is not implemented as stated in the documentation.

I tried:
`swagger{ apiSource{ excludePattern = 'someRegex' } }`
and I got this error message:
Could not set unknown property 'excludePattern' for com.benjaminsproule.swagger.gradleplugin.extension.ApiSourceExtension(apiModelPropertyAccessExclusionsList:null, typesToSkipList:null) of type com.benjaminsproule.swagger.gradleplugin.extension.ApiSourceExtension.

I am not sure if the syntax of calling excludePattern is wrong in my example.

Thanks,

Daniel

**Comment by gigaSproule** [comment]
:man_facepalming: I removed this because it wasn't actually being used anywhere in the code and implementing it would be more complicated than it was worth but didn't remove it from the README. If you are using it, I can try putting in the logic again.
