### ISSUE TITLE
OperationId value has "$default" appended to the method name

### ISSUE THREAD

**Issue by leonhsu1** [gigaSproule/swagger-gradle-plugin#74]
As the title says.

I have a method called "foo".

The operationId uses the method.getName() as found in the file https://github.com/gigaSproule/swagger-gradle-plugin/blob/master/src/main/groovy/com/benjaminsproule/swagger/gradleplugin/reader/SpringMvcApiReader.groovy#L188

When I look at the operationId, it appears as foo$default.

This only happens to one of the endpoints and all of them have the same settings.

**Comment by leonhsu1** [comment]
I figured out the issue. It was because in Kotlin, if you provide a default value, it'll automatically append $default to the method name.

`foo(bar: String = "hello")` causes the method name to result in `foo$default`

Removing this default value fixed it.

**Comment by gigaSproule** [comment]
Did not know that, thanks for updating.
