### ISSUE TITLE
gradle 4.7 deprecation warning

### ISSUE THREAD

**Issue by BenKalegin** [gigaSproule/swagger-gradle-plugin#75]
I am receiving a warning running generateSwaggerDocumentation:

`> Task :shared:generateSwaggerDocumentation`
The TaskInternal.execute() method has been deprecated and is scheduled to be removed in Gradle 5.0. There are better ways to re-use task logic, see https://docs.gradle.org/4.7/userguide/custom_tasks.html#sec:reusing_task_logic.

I think this is because of line `project.tasks.createSwaggerArtifact.execute()` in file `GenerateSwaggerDocsTask`

**Comment by gigaSproule** [comment]
Thanks for the issue, once I get through the more pressing issues, I will take a look at this (unless you wish to give it a go?)

**Comment by gigaSproule** [comment]
I've had to (probably correctly) re-work this to attach the json/yaml file to the artifacts. However, it then creates the issue that only 1 apiSource can be used (unless they have different formats) when using the maven-publish plugin. If just using the maven plugin and run `./gradlew install`, it creates multiple files perfectly fine (by abusing the classifier field).

**Comment by gigaSproule** [comment]
I've created a PR (#82) if you could take a look and see if the change fits your workflow. I don't use this feature and never really cared about it, it was just something that was part of the swagger-maven-plugin, so I included it here.
