### ISSUE TITLE
Task name "swagger" conflicts with other swagger related plugins

### ISSUE THREAD

**Issue by mubinahmed** [gigaSproule/swagger-gradle-plugin#8]
We are using swagger-codegen plugin to generate the REST client and we want to use swagger-gradle-plugin to generate the API Spec which will then be used by swagger-codegen. Since swagger-codegen also has a task name "swagger" there is a conflict and we cannot use the two plugins together. As per the best practices of Gradle plugin development, the task names should be very specific. Can you please update the task name or do you need a PR?

**Comment by gigaSproule** [comment]
By all means create a PR if you wish. I guess `generateSwaggerDocument` or something similar would be appropriate.

If you can't do it, I can do it later (commuting home at the moment)

**Comment by gigaSproule** [comment]
Just thinking, it's probably about time I updated to the latest version of swagger anyway, so I can do that at the same time.

**Comment by mubinahmed** [comment]
Thanks @gigaSproule. I will wait for that update. Do let me know if you need any assistance in doing that.

**Comment by gigaSproule** [comment]
released as version 0.1.0 with the task `generateSwaggerDocumentation`

**Comment by mubinahmed** [comment]
Thanks for the update & release. I thought you were going to close it, but since you didn't, I am closing this issue.

**Comment by gigaSproule** [comment]
Sorry, I completely forgot to do that! Thanks for closing it for me.
