### ISSUE TITLE
Provide a way to separate @Api and @ApiOperation

### ISSUE THREAD

**Issue by orfeonomia** [gigaSproule/swagger-gradle-plugin#81]
It would be nice to support some less centralized libraries/frameworks like Ratpack or Vert.x.
Currently, `@Api` has to annotate class and `@ApiOperation` has to annotate methods in the class.
It would be beneficial for Ratpack and Vertex (and others) to allow a separation because the libraries work with Handlers. Potentially there exist one class per each method (verb) and path combination.

Wouldn't it be cool if we have a new **`@ApiRef`** annotation to point to `@Api` location?
I suggest something like:
```
@Path("/path")
@Api(value = "api")
@Produces("application/json")
public class ApiClass {
	// empty api class
}

@ApiRef(ApiClass.class)      // my suggestion is to provide a "pointer" to an @Api location
public class OperationHandler {
    @GET
    @Path("/operationPath")
    @ApiOperation(value = "value",
            responseContainer = "List",
            response = String::class)
    public void handle(.........) {
		// handler method
    }
	...
}

@ApiRef(ApiClass.class)
public class Operation2Handler {    // another handler for the same API
    @POST
    @Path("/operationPath")
    @ApiOperation(value = "value",
            responseContainer = "List",
            response = String::class)
    public void handle(.........) {
		// handler method
    }
	...
}
```

**Comment by gigaSproule** [comment]
I see that you want to remove duplication of the `@Api` annotation, correct? Rather than adding in a new annotation and polluting production code with plugin specific annotations (which I kind of get is happening anyway with the Swagger annotations), I would like to think we can come up with a better solution. Maybe remove the requirement to have `@Api` as a config option? Not sure if it would work nicely, but could be worth a shot.

**Comment by orfeonomia** [comment]
Hi, thank you for your response. Yes, you are right. The @Api duplication is the problem I am trying to avoid. What you propose is even better idea than mine because @Api and @ApiOperation annotations are defined in swagger-core so to be able to add a new annotation (e.g. @ApiRef ) without problems one would have to modify the swagger-core.
I like your idea to completely skip @Api and to let the programmers use the @ApiOperation only.

**Comment by sharedprophet** [comment]
I have `@ApiOperation` only and the Maven Swagger plugin generates my spec just fine. Trying to convert to Gradle and this issue is how I'm learning that the lack of `@Api` annotations is why my spec is empty...

**Comment by gigaSproule** [comment]
Going to close this and have this tracked by #111 as to solve that, I will probably need to look at this
