### ISSUE TITLE
SpringMvc: @RequestMapping(path = "") is filtered

### ISSUE THREAD

**Issue by copa2** [gigaSproule/swagger-gradle-plugin#86]
```
@RestController
@RequestMapping("/api/example")
public class ExampleController {

        // GetMapping without path works and will be handled correctly
	@GetMapping
	public List<Permission> getExamples() {
		return ...
	}

        // GetMapping with empty path is filtered and not handled
	@GetMapping(path = "")
	public List<Permission> getExamples() {
		return ...
	}
}
```

Reason is https://github.com/gigaSproule/swagger-gradle-plugin/blob/master/src/main/groovy/com/benjaminsproule/swagger/gradleplugin/reader/SpringMvcApiReader.groovy#L434

Why is this empty check. Can this not be removed?

**Comment by gigaSproule** [comment]
I'll try to this fix this ASAP, but feel free to raise a PR if you want it sooner. Takes me 2 seconds to review a PR, but quite a bit more to find the time to develop the fix properly.
