### ISSUE TITLE
SpringMvc: Create default tags for @RestController

### ISSUE THREAD

**Issue by copa2** [gigaSproule/swagger-gradle-plugin#87]
When no special annotations are provided all operations have no tags and the SwaggerUI will list them under default. 
In case of SpringMVC (and also JAXRS) operations are normally put into context with the class they belong. 
Allow to configure a property so that all operations within a class will have a tag with the SimpleClassName of the class they belong.

**Comment by gigaSproule** [comment]
As with the other issue, feel free to raise a PR if you have the time. However, do you have a simple example I can quickly chuck into a test when I have some spare time, to make sure I don't screw it up?

**Comment by copa2** [comment]
Will try to provide a PR next week
