### ISSUE TITLE
Swagger: Allow to configure security keyword

### ISSUE THREAD

**Issue by copa2** [gigaSproule/swagger-gradle-plugin#88]
Currently it is possible to configure the `securityDefinitions`. Allow additionally to configure `security` on root level. This will be valid for all operations on the API.

see https://swagger.io/docs/specification/2-0/authentication/
> You use securityDefinitions to define all authentication types supported by the API, then use **security** to apply specific authentication types to the whole API or individual operations.

**Comment by gigaSproule** [comment]
Again, as with the others, feel free to raise a PR if you have the time, otherwise I will get to this ASAP.

**Comment by copa2** [comment]
Will try to provide a PR next week

**Comment by gigaSproule** [comment]
Merged in the PR
